### ISSUE TITLE
Unicode Keyerror

### ISSUE THREAD

**Issue by mainczjs** [olliethepikachu/MusicDownloader#4]
The following error traceback appeared when trying the tool out for the first time...

```
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib.py:1303: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  return ''.join(map(quoter, s))
Traceback (most recent call last):
  File "DeezerDownload.py", line 716, in <module>
    sys.exit(main())
  File "DeezerDownload.py", line 340, in main
    mainExC()
  File "DeezerDownload.py", line 704, in mainExC
    download_songs(sPlaylist, oldSearch)
  File "DeezerDownload.py", line 563, in download_songs
    '+'.join(urllib.quote_plus(artistName).split(' ')))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib.py", line 1310, in quote_plus
    return quote(s, safe)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib.py", line 1303, in quote
    return ''.join(map(quoter, s))
KeyError: u'\xe9'
```

**Comment by olliethepikachu** [comment]
Try downloading a song such as Starboy by The Weeknd. Does it error?

**Comment by olliethepikachu** [comment]
Closed due to inactivity.
